# Generated by Django 5.2 on 2025-04-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('health', 'Health'), ('fitness', 'Fitness'), ('learning', 'Learning'), ('personal', 'Personal')], max_length=20)),
                ('inspiration', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('3', '3 times a week'), ('5', '5 times a week')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
