# Generated by Django 5.2 on 2025-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_habit_updated_at_mood_intensity_mood_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='repetitions_required',
            field=models.IntegerField(default=1, help_text='Number of times this habit needs to be completed per day'),
        ),
    ]
