# Generated by Django 5.2 on 2025-05-11 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_habit_repetitions_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='repetitions_required',
        ),
        migrations.AddField(
            model_name='habit',
            name='required_repetitions',
            field=models.PositiveIntegerField(default=1, help_text='Number of times this habit must be completed per day'),
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_repetitions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tracker.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
