# Generated by Django 5.2 on 2025-05-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_habit_repetitions_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='habit',
            name='required_repetitions',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='completed_repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mood',
            name='intensity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('excited', 'Excited'), ('happy', 'Happy'), ('calm', 'Calm'), ('neutral', 'Neutral'), ('tired', 'Tired'), ('anxious', 'Anxious'), ('sad', 'Sad'), ('angry', 'Angry')], max_length=20),
        ),
    ]
