# Generated by Django 5.2 on 2025-05-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_created_at_mood_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='habit',
            name='weekly_frequency',
            field=models.IntegerField(default=1, help_text='How many times per week should this habit be completed?'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='required_repetitions',
            field=models.IntegerField(default=1, help_text='How many repetitions are required per completion?'),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.habit'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('energetic', 'Energetic'), ('focused', 'Focused'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('anxious', 'Anxious'), ('sad', 'Sad'), ('angry', 'Angry')], max_length=20),
        ),
    ]
